baseUrl = 'https://perk.pl/'
CanonifyUrls = true
languageCode = 'en-us'
title = 'Marcin "Perk" Stożek'
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  description = 'The home site of Marcin "Perk" Stożek'
  mainSections = ["posts", "talks"]
